<?php

class CubexTest extends PHPUnit_Framework_TestCase
{
  public function sampleProjectPath()
  {
    return dirname(__DIR__);
  }

  public function sampleProjectCubex()
  {
    return new \Cubex\Cubex($this->sampleProjectPath());
  }

  public function testConstruct()
  {
    $cubex = new \Cubex\Cubex(__DIR__);
    $this->assertEquals(__DIR__, $cubex->getDocRoot());
    $this->assertEquals(dirname(__DIR__), $cubex->getProjectRoot());
  }

  public function testExceptionWhenNoDocRootDefined()
  {
    $request = \Cubex\Http\Request::createFromGlobals();
    $cubex   = new \Cubex\Cubex();
    $this->setExpectedException('RuntimeException');
    $cubex->handle($request, \Cubex\Cubex::MASTER_REQUEST, false);
  }

  public function testConfiguration()
  {
    $config = new \Packaged\Config\Provider\Test\TestConfigProvider();
    $cubex  = new \Cubex\Cubex();
    $this->assertEquals(null, $cubex->getConfiguration());
    $this->assertEquals($cubex, $cubex->configure($config));
    $this->assertEquals($config, $cubex->getConfiguration());
  }

  public function testFlags()
  {
    $cubex = new \Cubex\Cubex();
    $this->assertFalse($cubex->hasFlag('test'));
    $cubex->setFlag('test');
    $this->assertTrue($cubex->hasFlag('test'));
    $cubex->setFlag('test', false);
    $this->assertFalse($cubex->hasFlag('test'));

    $cubex->setFlag('test');
    $cubex->unsetFlag('test');
    $this->assertFalse($cubex->hasFlag('test'));
  }

  public function testExceptions()
  {
    $cubex     = new \Cubex\Cubex();
    $exception = new Exception("Test Exception", 345);
    $resp      = $cubex->exceptionResponse($exception);
    $this->assertInstanceOf('Symfony\Component\HttpFoundation\Response', $resp);
    $this->assertContains('Uncaught Exception', (string)$resp);
    $this->assertContains('Test Exception', (string)$resp);
    $this->assertContains('345', (string)$resp);

    $exception = \Cubex\CubexException::debugException("msg", 123, 'solution');
    $resp      = $cubex->exceptionResponse($exception);
    $this->assertContains('msg', (string)$resp);
    $this->assertContains('123', (string)$resp);
    $this->assertContains('solution', (string)$resp);
  }

  public function testHandle()
  {
    $request = \Cubex\Http\Request::createFromGlobals();
    $cubex   = $this->sampleProjectCubex();
    $cubex->configure(new \Packaged\Config\Provider\Test\TestConfigProvider());
    $resp = $cubex->handle($request);
    $this->assertTrue($cubex->bound('request'));
    $this->assertInstanceOf('\Cubex\Http\Request', $cubex->make('request'));
    $this->assertInstanceOf('\Cubex\Http\Response', $resp);
  }

  public function testInvalidRequest()
  {
    $request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
    $cubex   = $this->sampleProjectCubex();

    $resp = $cubex->handle($request);
    $this->assertContains('Uncaught Exception', (string)$resp);
    $this->assertContains('You must use a \Cubex\Http\Request', (string)$resp);

    $this->setExpectedException(
      '\InvalidArgumentException',
      'You must use a \Cubex\Http\Request'
    );
    $cubex->handle(
      $request,
      \Cubex\Cubex::MASTER_REQUEST,
      false
    );

    $resp = $cubex->handle($request);
    $this->assertInstanceOf('Symfony\Component\HttpFoundation\Response', $resp);
    $this->assertContains('Uncaught Exception', (string)$resp);
    $this->assertContains('You must use a \Cubex\Http\Request', (string)$resp);
  }

  public function testTerminate()
  {
    $cubex = $this->sampleProjectCubex();
    $cubex->terminate(
      \Symfony\Component\HttpFoundation\Request::createFromGlobals(),
      new \Symfony\Component\HttpFoundation\Response('Hello World')
    );
  }

  public function testNoKernelProvidedException()
  {
    $this->setExpectedException(
      "RuntimeException",
      "No Cubex Kernel has been configured"
    );
    $cubex = new \Cubex\Cubex(__DIR__);
    $cubex->instance('\Cubex\Kernel\CubexKernel', new stdClass());
    $request = \Cubex\Http\Request::createFromGlobals();
    $cubex->handle($request, \Cubex\Cubex::MASTER_REQUEST, false);
  }

  public function testBrokenKernelProvidedException()
  {
    $cubex  = $this->sampleProjectCubex();
    $kernel = $this->getMock('\Cubex\Kernel\CubexKernel');
    $kernel->expects($this->any())
      ->method("handle")
      ->willReturn(null);
    $kernel->setCubex($cubex);

    $request = \Cubex\Http\Request::createFromGlobals();
    $cubex->instance('\Cubex\Kernel\CubexKernel', $kernel);
    $this->assertNull($kernel->handle($request));
    $this->setExpectedException(
      '\Cubex\CubexException',
      "A valid response was not generated by the default kernel",
      500
    );
    $cubex->handle($request, \Cubex\Cubex::MASTER_REQUEST, false);
  }

  /**
   * @runInSeparateProcess
   * @requires extension zlib
   */
  public function testGzipsResponse()
  {
    $request = \Cubex\Http\Request::createFromGlobals();

    $config = new \Packaged\Config\Provider\Test\TestConfigProvider();
    $config->addItem("response", 'gzip', true);

    $cubex = new \Cubex\Cubex(__DIR__);
    $cubex->configure($config);

    $kernel = $this->getMock('\Cubex\Kernel\CubexKernel');
    $kernel->expects($this->any())
      ->method("handle")
      ->willReturn(new \Cubex\Http\Response("Good Data"));
    $kernel->setCubex($cubex);

    $cubex->instance('\Cubex\Kernel\CubexKernel', $kernel);
    $cubex->handle($request, \Cubex\Cubex::MASTER_REQUEST, false);

    $this->assertEquals('On', ini_get('zlib.output_compression'));
  }

  public function testConfigure()
  {
    $config = new \Packaged\Config\Provider\Test\TestConfigProvider();
    $config->addItem("kernel", "project", 'Project');

    $cubex = new \Cubex\Cubex();
    $cubex->configure($config);
    $this->assertSame($config, $cubex->getConfiguration());
  }
}
