name: unit-test.yml
on: [ push, pull_request ]

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          coverage: xdebug
          tools: composer, phpunit
      - run: composer install -n --prefer-dist
      - run: php vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover=coverage.xml
      - run: php vendor/bin/coverage-check coverage.xml 70
